###########################################################
# Global Configuration (https://jekyllrb.com/docs/configuration/options/)
###########################################################
# if you want to force HTTPS, specify the domain without the http at the start
# set domain: "your_github_user_name.github.io"
domain: "Dallin-Moon.github.io"


remote_theme: pages-themes/architect@v0.2.0


# your web site url
# for GitHub Pages, url: "https://your_github_user_name.github.io"
url: "https://Dallin-Moon.github.io"

# path to this site
# if your page is located at https://your_github_user_name.github.io/blog, then set baseurl: "/blog"
baseurl: ""

# please use TZ database name column on the list table
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone: ""

###########################################################
# Markdown Options (https://jekyllrb.com/docs/configuration/markdown/)
# Configuring Jekyll in your GitHub Pages site (https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)
###########################################################
# This is default for GitHub Pages sites and cannot be changed.
highlighter: rouge
markdown: kramdown
kramdown:
  # This is default for GitHub Pages sites and cannot be changed.
  syntax_highlighter: rouge


###########################################################
# jekyll-redirect-from (https://github.com/jekyll/jekyll-redirect-from)
###########################################################
redirect_from:
  # Disabling generation of redirects.json
  json: false

###########################################################
# html compression (https://jch.penibelst.de)
###########################################################
compress_html:
  clippings: all
  comments: all
  #endings: all
  profile: false
  blanklines: false
  ignore:
    # disable this feature for development env.
    envs: [development]

###########################################################
# js compression (for removing comments(/**/only), line breaks and spaces)
# for debugging js files, simply set linebreak_and_space: false (in production env, this will be enabled automatically)
# for more info about environments (https://jekyllrb.com/docs/configuration/environments/)
###########################################################
compress_js:
  # enable or disable line breaks and space removal feature for development env.
  linebreak_and_space: false
  # disable this feature entirely for development or production env.
  #ignore: development

###########################################################
# Sass (https://jekyllrb.com/docs/assets/)
###########################################################
sass:
  sass_dir: assets/_scss
  # enable css compression
  style: compressed

###########################################################
# Exclude these files or folders from production site
###########################################################
exclude: ["Gemfile*", "vendor", ".github", ".vscode", "README*", "CODE_OF_CONDUCT.md", "LICENSE", "docs"]
